"""updated password column

Revision ID: 16022f3d314e
Revises: 217174519620
Create Date: 2024-02-08 15:40:50.927902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16022f3d314e'
down_revision = '217174519620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
