"""adjusted the tables

Revision ID: 972a8652f12d
Revises: 
Create Date: 2024-02-26 11:42:29.036732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972a8652f12d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
