"""Add user_id column to Shop model

Revision ID: d2e68b2d8454
Revises: 7664c2a0ecb8
Create Date: 2024-02-11 19:09:30.200335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e68b2d8454'
down_revision = '7664c2a0ecb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("shop-user", 'users', ['user_id'], ['id'])
 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_constraint("shop_user", type_='foreignkey')

        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
